<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="THORPC" name="Main Test Group" tests="21" failures="1" timestamp="29 Apr 2014 01:34:54 GMT" time="18.814" errors="0">
  <testcase name="@BeforeMethod setUp" time="0.0" classname="qa.tests.BeforeTestSkip">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="arraysFailures_3" time="0.001" classname="qa.tests.BeforeTestSkip">
    <skipped/>
  </testcase> <!-- arraysFailures_3 -->
  <testcase name="arraysFailures_1" time="0.627" classname="qa.tests.AssertTests2"/>
  <testcase name="setsSuccess" time="1.409" classname="qa.tests.FailTest"/>
  <testcase name="setsSuccess" time="1.477" classname="qa.tests.SkipTest"/>
  <testcase name="arraysFailures_2" time="1.064" classname="qa.tests.AssertTests2"/>
  <testcase name="showFailure" time="0.701" classname="qa.tests.FailTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at qa.tests.FailTest.showFailure(FailTest.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- showFailure -->
  <testcase name="arraysFailures_3" time="0.756" classname="qa.tests.AssertTests2"/>
  <testcase name="arraysFailures_1" time="2.539" classname="qa.tests.AssertTests1"/>
  <testcase name="testSkipException" time="1.734" classname="qa.tests.SkipTest">
    <skipped/>
  </testcase> <!-- testSkipException -->
  <testcase name="intArray_Issue4" time="1.214" classname="qa.tests.AssertTests2"/>
  <testcase name="int_Integer_Arrays" time="0.723" classname="qa.tests.AssertTests2"/>
  <testcase name="arraysFailures_2" time="2.646" classname="qa.tests.AssertTests1"/>
  <testcase name="noOrderFailure" time="2.889" classname="qa.tests.AssertTests2"/>
  <testcase name="arraysFailures_3" time="2.406" classname="qa.tests.AssertTests1"/>
  <testcase name="noOrderSuccess" time="0.676" classname="qa.tests.AssertTests2"/>
  <testcase name="intArray_Issue4" time="1.913" classname="qa.tests.AssertTests1"/>
  <testcase name="setsSuccess" time="1.58" classname="qa.tests.AssertTests2"/>
  <testcase name="int_Integer_Arrays" time="2.465" classname="qa.tests.AssertTests1"/>
  <testcase name="noOrderFailure" time="2.418" classname="qa.tests.AssertTests1"/>
  <testcase name="noOrderSuccess" time="1.791" classname="qa.tests.AssertTests1"/>
  <testcase name="setsSuccess" time="2.622" classname="qa.tests.AssertTests1"/>
</testsuite> <!-- Main Test Group -->
